USE JobApplication;

LOAD DATA INFILE '/tmp/CompanyCategory.csv' INTO TABLE CompanyCategory
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/Company.csv' INTO TABLE Company
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/CompanyImage.csv' INTO TABLE CompanyImage
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/UserType.csv' INTO TABLE UserType
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/UserAccount.csv' INTO TABLE UserAccount
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/UserLog.csv' INTO TABLE UserLog
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/SeekerProfile.csv' INTO TABLE SeekerProfile
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/EducationDetail.csv' INTO TABLE EducationDetail
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/ExperienceDetail.csv' INTO TABLE ExperienceDetail
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/WorkType.csv' INTO TABLE WorkType
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/JobLocation.csv' INTO TABLE JobLocation
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/Job.csv' INTO TABLE Job
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/JobApplyActivity.csv' INTO TABLE JobApplyActivity
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/SkillSet.csv' INTO TABLE SkillSet
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/SeekerSkillSet.csv' INTO TABLE SeekerSkillSet
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;
    
LOAD DATA INFILE '/tmp/JobPostSkillSet.csv' INTO TABLE JobPostSkillSet
	FIELDS TERMINATED BY ',' ENCLOSED BY '"'
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;