package job.model;

public class JobLocation {
	protected int jobLocationId;
	protected String streetAddress;
	protected String city;
	protected String state;
	protected String country;
	protected String zip;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the JobLocationId.
	public JobLocation(int jobLocationId, String streetAddress, String city, String state, String country, String zip) {
		this.jobLocationId = jobLocationId;
		this.streetAddress = streetAddress;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zip = zip;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the JobLocationId,
	// such as a foreign key reference to JobLocationId.
	// Given JobLocationId, we can fetch the full JobLocation record.
	public JobLocation(int jobLocationId) {
		this.jobLocationId = jobLocationId;
	}
	
	// This constructor can be used for creating new records, where the JobLocationId may not be
	// assigned yet since it is auto-generated by MySQL.
	public JobLocation(String streetAddress, String city, String state, String country, String zip) {
		this.streetAddress = streetAddress;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zip = zip;
	}

	public int getJobLocationId() {
		return jobLocationId;
	}

	public void setJobLocationId(int jobLocationId) {
		this.jobLocationId = jobLocationId;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}	
}
